#ifndef KEYBOARD_MATRIX_H
#define KEYBOARD_MATRIX_H

#include "bsp_matrix_size.h"

// 总扫描按键数量
#define TOTAL_SCAN_KEY_COUNT (GROUP_MAXNUM * ADC_VALUE_MAXNUM * ADC_CHANNEL_MAXNUM)

// 按键分组的一维索引
#define KEY_GROUP_INDEX_1 ADC_VALUE_MAXNUM
// 按键分组的二维索引
#define KEY_GROUP_INDEX_2 ADC_CHANNEL_MAXNUM
// 按键分组的三维索引
#define KEY_GROUP_INDEX_3 GROUP_MAXNUM

#define ADC_VALUE_MAXNUM  BSP_ADC_VALUE_MAXNUM
#define ADC_CHANNEL_MAXNUM BSP_ADC_CHANNEL_MAXNUM
#define GROUP_MAXNUM BSP_GROUP_MAXNUM

#endif
